config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do 
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end
  
  resources :comments
  resources :tours  
  get 'feed', to: 'tours#index', as: :feed
   root to: "tours#index"

 end

app/models/comment.rb
class Comment < ActiveRecord::Base
    attr_accessor :comment, :user_id
    belongs_to :user
end

app/models/tour.rb
class Tour < ActiveRecord::Base
      has_many :users

    def self.search(search)
        where("Type_of_tour ILIKE ?", "%#{search})%")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
        # Include default devise modules. Others available are:
        # :confirmable, :lockable, :timeoutable and :omniauthable
        devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         #attr_accessor :email, :password, :password_confirmation, :remember_me,
                #:first_name, :last_name, :profile_name     (commented out as attr accessor is giving errors) 
        
        #user has many tours
        has_many :tours
   
            #conaticates first_name and last_name into full_name
        def full_name
            first_name + " " + last_name
        end
            #adds gravatar image to project
        def gravatar_url
            stripped_email = email.strip
            downcased_email = stripped_email.downcase
            hash = Digest::MD5.hexdigest(downcased_email)
     
            "http://gravatar.com/avatar/#{hash}"
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:Name, :Comment)
    end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  #def info
    #@tours = Tour.all
  #end
  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
    if params[:search]
        @tours = Tour.search(params[:search]).order("created_at DESC")
      else
        @tours = Tour.all.order('created_at DESC')
    end
  end
  
  def index
    @tours = Tour.all
  end
  
  
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:Type_of_tour, :Date_of_tour, :Time_of_tour)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment, html: { class: 'form-horizontal' }) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

         <ul>
          <% @comment.errors.full_messages.each do |message| %>
         <li><%= message %></li>
  <% end %>
         </ul>
    </div>
  <% end %>
        <%#= form.input  :user_id, collection: User.all, label_method: :full_name %><br>
        <%= form.input  :Name %><br>
        <%= form.input  :Comment %>
    <div class="form-actions">
        <%= form.button :submit %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"></p>
      <div class="page-header">
        <h1>All Comments</h1>
      </div>
   
       <%# everthing in this loop gets printed for each  comment on the page hf%>
    <% @comments.each do |comments| %>
       <div class="comment">
          <div class="row">
             <div class="span1">
               gravatr
              <%#= image_tag comments.user.gravatar_url %> 
             </div>
          <div class="span7">
              <strong><%= comments.Name %></strong>
              <p><%= comments.Comment %></p>
          <div class="meta">
                  <%# I put these in differnt spans so I could change the way the links are displayed with out efedcting each otherf%>
              <%= link_to time_ago_in_words(comments.created_at) + " ago", comments  %> |
              <%= link_to "Show", comments %> |
                  <%# I put these in differnt continers so I could change the way the links are displayedf%>
          <span class="admin">
              <%= link_to "Edit", edit_comment_path(comments) %> |
              <%= link_to "Destroy", comments, method: :delete, data:{ confirm: "Are you sure you want to delete" } %>
          </span>
          </div>
          </div>
          </div>
        </div>
<% end %>
          <%= link_to 'New Comment', new_comment_path,  class: "btn"%>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"></p>
<p>
  <strong>Name:</strong>
  <%#= @comment.user.First_Name %> 
</p>
<p>
  <strong>Comment:</strong>
  <%= @comment.Comment %>
</p>

    <%= link_to 'Edit', edit_comment_path(@comment) %> |
    <%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
</html>
<!DOCTYPE html>
<html>
<head>
  <title>DublinTours</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
        <div class="navbar navar-fixed-top">
            <div class="navbar-inner">
                 <div class="container">
                 <ul class="nav pull-right">
                     <li><%= link_to "Logout", logout_path %></li>
                 </ul>
                 <ul class="nav pull-right">
                     <li><%= link_to "Register", register_path%></li>
                 </ul>
                 <ul class="nav pull-right">
                     <li><%= link_to "Login", login_path%></li>
                 </ul>
                 <ul class="nav pull-left">
                     <li><%= link_to "Tours", tours_path%></li> 
                 </ul>
                 <ul class="nav pull-left">
                     <li><%= link_to "Comments", comments_path%></li> 
                 </ul>
                        
                </div>
            </div>
        </div>
            <div class="container">
          <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
            <%= yield %>
            <p>Copyright &copy; Students Website <?php echo date("Y"); ?> </p>
        </div>
</body>
</html>

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>
        <ul>
          <% @tour.errors.full_messages.each do |message| %>
          <li><%= message %></li>
       <% end %>
         </ul>
       </div>
  <% end %>
  <%#= code for dropdown menue %>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Dropdown
            <span class="caret">
            </span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><a href="#">Hiking</a></li>
          <li><a href="#">Walking</a></li>
          <li><a href="#">Museum</a></li>
          </ul>
        </div>

        <div class="field">
          <%= f.label :Type_of_tour %><br>
          <%= f.text_field :Type_of_tour %>
        </div>
        <div class="field">
           <%= f.label :Date_of_tour %><br>
           <%= f.date_select :Date_of_tour %>
        </div>
        <div class="field">
            <%= f.label :Time_of_tour %><br>
            <%= f.time_select :Time_of_tour %>
        </div>

        <div class="actions">
            <%= f.submit %>
        </div>
    <% end %>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<p id="notice"></p>
<%= form_tag(tours_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search tours by type of tour" %>
<%= submit_tag "search" %>
<% end %>
        <div class="page-header">
               <h1>All Trips</h1>
        </div>
             <% @tours.each do |tours| %>
        <div class="tours">
             <strong><%= tours.Type_of_tour %></strong>
             <p><%= tours.Date_of_tour%></p>
             <p><%= tours.Time_of_tour %></p>
        <div class="meta">
             <%#= link_to time_ago_in_words(trip.created_at) + " ago", trip %> |
             <%= link_to "Show", tours %> |
        <span class="admin">
              <%= link_to "Edit", edit_tour_path(tours) %> |
         </span>
         </div>
         </div>
 <% end %>
 <%= link_to 'New Tour', new_tour_path, class: "btn" %>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"></p>

<p>
  <strong>Type of tour:</strong>
  <%= @tour.Type_of_tour %>
</p>

<p>
  <strong>Date of tour:</strong>
  <%= @tour.Date_of_tour %>
</p>

<p>
  <strong>Time of tour:</strong>
  <%= @tour.Time_of_tour %>
</p>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>